Add Data.TypeMap.Dynamic
Lysxia/type-map pull request #3
Opened 2018-11-06 21:27 UTC by deepfire

Will drop removal of the upper bound on base if you would prefer that way.

2018-11-06 21:42 UTC, Lysxia requested changes
Thanks! Would you also like to add the corresponding function to the `Dynamic.Alt` module (that uses `TypeApplications`)? Otherwise it's still fine. There's just this one comment to address.

2018-11-06 21:42 UTC, Lysxia commented on src/Data/TypeMap/Internal/Dynamic.hs
> +update t f (TypeMap m) = TypeMap (Map.update (coerceA . f . coerceB) (typeRep t) m)
Could this be `Map.update (coerce f)`, so this would not create an additional closure around `f`?

2018-11-07 17:27 UTC, deepfire commented
@Lysxia, done!

2018-11-07 17:27 UTC, deepfire commented on src/Data/TypeMap/Internal/Dynamic.hs
> +update t f (TypeMap m) = TypeMap (Map.update (coerceA . f . coerceB) (typeRep t) m)
Done, good point, didn't think of that!

2018-11-07 18:01 UTC, Lysxia approved these changes

2018-11-07 18:02 UTC, Lysxia commented
Great, thanks! I'll make a new release some time in the week end.

2018-11-07 18:02 UTC, merged

2018-11-10 17:45 UTC, Lysxia commented
Now in [`0.1.3.0`](https://hackage.haskell.org/package/type-map-0.1.3.0)!

2018-11-14 16:27 UTC, deepfire commented
Thank you, Li-Yao!